Host *
  IdentityAgent /Users/toof/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh

Host linux zen2
  HostName zen2
  # Forward the Secretive agent so git can sign with the enclave key on zen2
  ForwardAgent /Users/toof/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
  RemoteForward /run/user/1000/gnupg/S.gpg-agent /Users/toof/.gnupg/S.gpg-agent
  StreamLocalBindUnlink yes
