[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['cpp']

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# on_ft = ['cpp']
# rev = 'next'
# build = 'bash install.sh'
# hook_add = '''
#   set hidden
# 
#   let g:LanguageClient_serverCommands = {
#     \ }
# 
#   nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
#   nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
#   nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
# '''
