#[[plugins]]
#repo = 'zchee/deoplete-jedi
#on_ft = ['python']

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['cpp']

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
on_ft = ['cpp', 'python']
rev = 'next'
build = 'bash install.sh'
hook_add = '''
  set hidden

  let g:LanguageClient_serverCommands = {
    \ 'cpp': ['ccls'],
    \ 'python': ['/usr/bin/pyls']
    \ }

  nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
  nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
  nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
  let g:LanguageClient_autoStart = 1
  let g:LanguageClient_diagnosticsEnable = 0
  let g:LanguageClient_hasSnippetSupport = 0
'''

#[[plugins]]
#repo = 'prabirshrestha/async.vim'
#on_ft = ['c', 'cpp', 'python']
#
#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'
#on_ft = ['c', 'cpp', 'python']
#hook_add = '''
#  let g:lsp_diagnostics_enabled = 0         " disable diagnostics support
#  if executable('ccls')
#    au User lsp_setup call lsp#register_server({
#      \ 'name': 'ccls',
#      \ 'cmd': {server_info->['ccls']},
#      \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
#      \ 'initialization_options': { 'cacheDirectory': '/tmp/ccls' },
#      \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
#      \ })
#  endif
#
#  let g:deoplete#enable_at_startup = 1
#
#  if executable('pyls')
#      " pip install python-language-server
#      au User lsp_setup call lsp#register_server({
#          \ 'name': 'pyls',
#          \ 'cmd': {server_info->['pyls']},
#          \ 'whitelist': ['python'],
#          \ })
#  endif
#'''
#
#   " For python language server
#   if (executable('pyls'))
#       let s:pyls_path = fnamemodify(g:python_host_prog, ':h') . '/'. 'pyls'
#       augroup LspPython
#           autocmd!
#           autocmd User lsp_setup call lsp#register_server({
#         \ 'name': 'pyls',
#         \ 'cmd': {server_info->['pyls']},
#         \ 'whitelist': ['python']
#         \ })
#       augroup END
#   endif
# '''
# 
# [[plugins]]
# repo = 'lighttiger2505/deoplete-vim-lsp'
# on_ft = ['c', 'cpp', 'python']

#[[plugins]]
#repo = 'thomasfaingnaert/vim-lsp-snippets'
#on_ft = ['c', 'cpp', 'python']
#
#[[plugins]]
#repo = 'thomasfaingnaert/vim-lsp-neosnippet'
#on_ft = ['c', 'cpp', 'python']
