[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tyrannicaltoucan/vim-quantum'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
      \ 'colorscheme': 'quantum',
      \ }
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'ap/vim-css-color'
